### ISSUE TITLE
Couleur Titre - problème thème light et dark

### ISSUE THREAD

**Issue by Caelion** [TiTidom-RC/Monitoring#197]
Bonjour Titidom,
Voici un problème sur la couleur en thème light et thème dark
D11 / J4.4.19 / Monitoring et SSH Manager uptodate en stable

Le widget est fait de tel manière qu'il applique en thème light ce css :
![image](https://github.com/user-attachments/assets/39c2b88e-6211-43b7-b494-853abca01766)

Ce qui donne ce résultat :
![image](https://github.com/user-attachments/assets/545a4a13-b6ca-424b-89be-76085dcb5a16)

Et en thème dark :
![image](https://github.com/user-attachments/assets/df36315e-fee8-416c-8182-00f55a715f94)

Ce qui donne ce résultat :
![image](https://github.com/user-attachments/assets/4aee9c0e-2ad9-410a-9ae2-8f11513a9b61)

Ce qui donne une couleur plus clair que les widgets standard du core :
![image](https://github.com/user-attachments/assets/7f5e14ac-9d70-4218-b337-2ac7ce8820d3)

Un widget standard :
Light :
![image](https://github.com/user-attachments/assets/34e935c6-b65d-444f-844f-9a70da07f541)

Dark :
![image](https://github.com/user-attachments/assets/0dbc68e2-a15e-413f-b02b-00b6983851e4)

Je ne te propose pas de PR car sur mon autre ticket, tu m'as dit : `En l'état, je ne peux faire plus, car sinon cela a une incidence sur l'affichage souhaité du Widget.` mais je ne sais pas ce qu'est l'affichage souhaité.
Je corrige donc de mon côté après tes updates

Bien à toi,

**Comment by TiTidom-RC** [comment]
Bonjour,

Pour le coup, ici c'est bien un bug, et ce n'est pas voulu. Dans mes tests (comme sur tous mes Jeedom) j'utilise les catégories colorées, ce qui semble masquer ce soucis.

**Comment by TiTidom-RC** [comment]
C'est corrigé dans la version 3.1.3.

Merci.

**Comment by Caelion** [comment]
Ok merci
Pour info, voici le résultat après l'update :
- ok pour les couleurs
- par contre les titres sont tronqués :
![image](https://github.com/user-attachments/assets/5c688676-eace-44aa-b11c-73da659193b9)
![image](https://github.com/user-attachments/assets/b2632813-4e5f-4648-876a-bcb67c27b254)
