### ISSUE TITLE
Champ état connexion SSH non totalement invisible pour l'équipement local

### ISSUE THREAD

**Issue by Caelion** [TiTidom-RC/Monitoring#201]
Autre modification CSS :
L'information de SSH OK / KO en haut à gauche du widget : elle est vide sur l'équipement local mais il reste la trace du margin-right de 3px :
![image](https://github.com/user-attachments/assets/4d148c0f-cfe8-4c84-b309-f0ea4bec3b5e)
(la partie violette)

**Comment by TiTidom-RC** [comment]
Merci pour cette remontée 👍 

Je viens de faire une modification dans le CSS pour masquer cette margin-right dans ce cas là, tu me diras dans la prochaine béta qui va sortir (v3.1.4)
